// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type City struct {
	Name string  `json:"name"`
	Lat  float64 `json:"lat"`
	Lon  float64 `json:"lon"`
}

type InputFilter struct {
	HasPhoto           bool    `json:"hasPhoto"`
	InContact          bool    `json:"inContact"`
	Favourite          bool    `json:"favourite"`
	CompatibilityScore float64 `json:"compatibilityScore"`
	Age                *Range  `json:"age"`
	Height             *Range  `json:"height"`
	DistanceInKm       *Range  `json:"distanceInKm"`
}

type Match struct {
	DisplayName        string  `json:"displayName"`
	Age                int     `json:"age"`
	JobTitle           string  `json:"jobTitle"`
	HeightInCm         int     `json:"heightInCm"`
	City               *City   `json:"city"`
	MainPhoto          *string `json:"mainPhoto"`
	CompatibilityScore float64 `json:"compatibilityScore"`
	ContactsExchanged  int     `json:"contactsExchanged"`
	Favourite          bool    `json:"favourite"`
	Religion           string  `json:"religion"`
}

type Range struct {
	From int `json:"from"`
	To   int `json:"to"`
}
